apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ceneka
  namespace: ceneka
spec:
  kafka:
    version: 3.3.1
    replicas: 1
    listeners:
      - name: internal
        type: internal
        port: 9092
        tls: false
      - name: external
        type: loadbalancer
        tls: false
        port: 9094
    authorization:
      type: simple
      superUsers:
        - kafka-admin
        - ANONYMOUS
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    userOperator:
      reconciliationIntervalSeconds: 157680000
      logging:
        type: inline
        loggers:
          rootLogger.level: DEBUG
    topicOperator:
      reconciliationIntervalSeconds: 157680000
      logging:
        type: inline
        loggers:
          rootLogger.level: DEBUG
      resources:
        requests:
          memory: 200Mi
          cpu: 200m
        limits:
          memory: 300Mi
          cpu: 500m