apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  rabbitmq:
    additionalConfig: |
      default_user=ceneka
      default_pass=ceneka_data_23